#!/opt/homebrew/bin/bash

# ==============================================================================
# OLLAMA MODEL PRUNER
# Identifies installed models not defined in the current profile
# and provides an interactive interface to remove them.
#
# Usage:
#   ./prune_models.sh                  # auto-detect profile
#   ./prune_models.sh macbook-m5-64gb  # specify profile
# ==============================================================================

set -euo pipefail

PROFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load helpers for profile detection
SETTINGS_BASE="$(cd "$PROFILES_DIR/.." && pwd)"
if [[ -f "$SETTINGS_BASE/helpers.sh" ]]; then
    . "$SETTINGS_BASE/helpers.sh"
fi

# ------------------------------------------------------------------------------
# Resolve profile
# ------------------------------------------------------------------------------
# Parse arguments: profile [keep...]
PROFILE=""
declare -a KEEP_MODELS=()
for arg in "$@"; do
    if [[ -z "$PROFILE" ]]; then
        PROFILE="$arg"
    else
        KEEP_MODELS+=("$arg")
    fi
done
# Also support PRUNE_KEEP env var (space-separated or comma-separated)
if [[ -n "${PRUNE_KEEP:-}" ]]; then
    IFS=', ' read -ra extra <<< "$PRUNE_KEEP"
    KEEP_MODELS+=("${extra[@]}")
fi
unset extra

if [[ -z "$PROFILE" ]]; then
    PROFILE="${MACHINE_PROFILE}"
fi

if [[ -z "$PROFILE" ]]; then
    echo "Error: Could not auto-detect profile. Pass a profile name as argument."
    echo "Available profiles:"
    ls -d "$PROFILES_DIR"/*/ 2>/dev/null | while read -r d; do
        echo "  $(basename "$d")"
    done
    exit 1
fi

MODELS_SH="$PROFILES_DIR/$PROFILE/models.sh"

if [[ ! -f "$MODELS_SH" ]]; then
    echo "Error: $MODELS_SH not found."
    exit 1
fi

echo "Profile: $PROFILE"
echo "Config:  $MODELS_SH"

# Source the models configuration
source "$MODELS_SH"

# Temporary files for tracking
REQUIRED_MODELS_FILE=$(mktemp)
REASON_MAP_FILE=$(mktemp)
trap 'rm -f "$REQUIRED_MODELS_FILE" "$REASON_MAP_FILE"' EXIT

# Helper to register a required model and its reason
register_model() {
    local model_str="$1"
    local reason="$2"

    # Trim whitespace
    model_str=$(echo "$model_str" | xargs)
    if [[ -n "$model_str" ]]; then
        echo "$model_str" >> "$REQUIRED_MODELS_FILE"
        echo "$model_str|$reason" >> "$REASON_MAP_FILE"
    fi
}

# Check for authoritative required-models.txt (generated by deploy_configs)
REQFILE="$HOME/.ollama/required-models.txt"
if [[ -f "$REQFILE" ]]; then
    echo "Using authoritative list: $REQFILE"
    while IFS= read -r line; do
        # Stop at cloud section — only LOCAL models are pruned
        if [[ "$line" == *"CLOUD MODELS"* ]]; then
            break
        fi
        line="${line%%#*}"          # strip comments
        line="$(echo "$line" | xargs)"  # trim whitespace
        [[ -z "$line" ]] && continue
        register_model "$line" "From $REQFILE"
    done < "$REQFILE"
else
    echo "Analyzing requirements from $MODELS_SH..."

    # 1. Process canonical local GGUF-backed Ollama models
    if declare -p LOCAL_MODEL_NAMES &>/dev/null; then
        for alias in "${LOCAL_MODEL_NAMES[@]}"; do
            register_model "$alias" "Defined in LOCAL_MODEL_NAMES"

            local variants="${GGUF_VARIANTS[$alias]:-}"
            if [[ -n "$variants" ]]; then
                IFS=',' read -ra _variant_specs <<< "$variants"
                for spec in "${_variant_specs[@]}"; do
                    spec="$(echo "$spec" | sed 's/^ *//;s/ *$//')"
                    [[ -z "$spec" ]] && continue
                    IFS='|' read -r extra_quant _extra_filename _extra_source <<< "$spec"
                    [[ -z "$extra_quant" ]] && continue
                    local safe_quant
                    safe_quant="$(echo "$extra_quant" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g; s/--*/-/g; s/^-//; s/-$//')"
                    register_model "${alias}-${safe_quant}" "GGUF variant of $alias ($extra_quant)"
                done
            fi
        done
    fi

    # 2. Process OPENCODE_AGENTS
    if declare -p OPENCODE_AGENTS &>/dev/null; then
        for agent in "${!OPENCODE_AGENTS[@]}"; do
            register_model "${OPENCODE_AGENTS[$agent]}" "Used by OpenCode agent: $agent"
        done
    fi

    # 3. Process CONTINUE_ROLES
    if declare -p CONTINUE_ROLES &>/dev/null; then
        for role in "${!CONTINUE_ROLES[@]}"; do
            register_model "${CONTINUE_ROLES[$role]}" "Used by Continue role: $role"
        done
    fi

    # 4. Dynamically discover all other scalar model variables
    for var in $(compgen -v); do
        declare -p "$var" &>/dev/null || continue
        [[ "$(declare -p "$var" 2>/dev/null)" == "declare -"* ]] && continue
        val="${!var:-}"
        [[ -z "$val" ]] && continue
        case "$var" in
            LOCAL_MODEL_NAMES|GGUF_SOURCES|GGUF_QUANTS|GGUF_FILENAMES|GGUF_LOCAL_FILENAMES|GGUF_REMOTE_FILENAMES|GGUF_FAMILIES|GGUF_VARIANTS|OLLAMA_CONTEXT_WINDOWS|MODELFILE_PARAMS|OLLAMA_MODELFILE_PARAMS|OLLAMA_MODELFILE_TEMPLATES|OPENCODE_AGENTS|CONTINUE_ROLES|OPENROUTER_MODELS|OLLAMA_CLOUD_MODELS) continue ;;
            BASH*|COMP*|DIRSTACK|FUNCNAME|GROUPS|PIPESTATUS|SHLVL|_|RANDOM|SECONDS|LINENO|OPTERR) continue ;;
            PROFILE|PROFILES_DIR|SETTINGS_BASE|MODELS_SH|REQUIRED_MODELS_FILE|REASON_MAP_FILE) continue ;;
            DATE|BACKUP_DIR|HW_MODEL|HW_MEM_GB|REPO_ROOT|NC|BLUE|GREEN|PURPLE|RED|YELLOW) continue ;;
            *_CLOUD) continue ;;
        esac
        if [[ "$val" == *":"* ]] && [[ "$val" != /* ]] && [[ "$val" != *"/"* ]]; then
            register_model "$val" "Used by variable: $var"
        fi
    done

    # 5. Register explicit local aliases from OLLAMA_CONTEXT_WINDOWS
    if declare -p OLLAMA_CONTEXT_WINDOWS &>/dev/null; then
        for base_model in "${!OLLAMA_CONTEXT_WINDOWS[@]}"; do
            local contexts="${OLLAMA_CONTEXT_WINDOWS[$base_model]}"
            local ctx_value suffix first_ctx=1
            for ctx_value in $contexts; do
                if [[ $first_ctx -eq 1 ]]; then
                    register_model "$base_model" "Configured local alias (num_ctx=$ctx_value)"
                    first_ctx=0
                else
                    if (( ctx_value % 1024 == 0 )); then
                        suffix="$((ctx_value / 1024))k"
                    else
                        suffix="$ctx_value"
                    fi
                    register_model "${base_model}-${suffix}" "Configured context alias of $base_model (num_ctx=$ctx_value)"
                fi
            done
        done
    fi
fi

# Append any user-specified keep models from arguments
if [[ ${#KEEP_MODELS[@]} -gt 0 ]]; then
    for km in "${KEEP_MODELS[@]}"; do
        register_model "$km" "User-requested keep"
    done
fi

# Get unique list of required models
sort -u "$REQUIRED_MODELS_FILE" -o "$REQUIRED_MODELS_FILE"

# Get currently installed models from Ollama
INSTALLED_MODELS=$(ollama list 2>/dev/null | tail -n +2 | awk '{print $1}')

declare -a REQUIRED_LINES=()
OBSOLETE_MODELS=()

if [[ -z "$INSTALLED_MODELS" ]]; then
    echo "(no models installed)"
fi

while read -r installed; do
    [[ -z "$installed" ]] && continue
    # Treat :latest as equivalent to tagless (e.g. nomic-embed-text:latest ≈ nomic-embed-text)
    _match="${installed%:latest}"
    if grep -q "^${_match}$" "$REQUIRED_MODELS_FILE"; then
        reason=$(grep "^${_match}|" "$REASON_MAP_FILE" | cut -d'|' -f2 | head -n 1 || true)
        REQUIRED_LINES+=("$(printf "%-35s %s" "$installed" "$reason")")
    else
        OBSOLETE_MODELS+=("$installed")
    fi
done <<< "$INSTALLED_MODELS"

echo -e "\n=== REQUIRED MODELS (INSTALLED) ==="
printf "%-35s %s\n" "MODEL" "REASON"
echo "--------------------------------------------------------------------------------"
printf "%s\n" "${REQUIRED_LINES[@]}" | sort -f

if [ ${#OBSOLETE_MODELS[@]} -eq 0 ]; then
    echo -e "\nNo obsolete models found. Your installation is clean!"
    exit 0
fi

# Sort obsolete models alphabetically
IFS=$'\n' OBSOLETE_MODELS=($(sort -f <<<"${OBSOLETE_MODELS[*]}"))
unset IFS

echo -e "\n=== OBSOLETE MODELS (NOT IN CONFIG) ==="
echo "The following models are installed but not required by profile: $PROFILE"
echo "Use SPACE to select models for removal, ENTER to confirm."

# Check for fzf
if command -v fzf >/dev/null 2>&1; then
     SELECTED_MODELS=$(printf "%s\n" "${OBSOLETE_MODELS[@]}" | fzf --multi --header "Select models to DELETE (Space=Select, Enter=Confirm)" --bind 'space:toggle')

    if [[ -n "$SELECTED_MODELS" ]]; then
        echo -e "\nRemoving selected models..."
        while read -r model; do
            echo "Removing $model..."
            ollama rm "$model"
        done <<< "$SELECTED_MODELS"
        echo "Pruning complete."
    else
        echo "No models selected for removal."
    fi
else
    echo "Error: 'fzf' is not installed. Interactive selection is unavailable."
    echo "Please install fzf via 'brew install fzf' for the best experience."
    echo ""
    echo "Obsolete models:"
    printf "  %s\n" "${OBSOLETE_MODELS[@]}"
    exit 1
fi
