#!/opt/homebrew/bin/bash
# generate-model-map.sh — Generate mermaid diagram of model→tool→config flow
set -euo pipefail

PROFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILE="${1:-${MACHINE_PROFILE:-}}"

if [[ -z "$PROFILE" ]]; then
    echo "Usage: $0 <profile-name>"
    echo "Available:"
    ls -d "$PROFILES_DIR"/*/ 2>/dev/null | while read -r d; do echo "  $(basename "$d")"; done
    exit 1
fi

MODELS_SH="$PROFILES_DIR/$PROFILE/models.sh"
[[ -f "$MODELS_SH" ]] || { echo "Error: $MODELS_SH not found."; exit 1; }
source "$MODELS_SH"

link() {
    local model="$1" tool="$2"
    [[ -z "$model" ]] && return
    TOOLS_BY_MODEL["$model"]="${TOOLS_BY_MODEL["$model"]:-},${tool}"
    TOOLS_BY_MODEL["$model"]="${TOOLS_BY_MODEL["$model"]#,}"
}

declare -A TOOLS_BY_MODEL=()

link "${CLINE_MODEL:-}" "Cline"
link "${CLINE_MODEL_CLOUD:-}" "Cline"
link "${ZOOCODE_MODEL:-}" "ZooCode"
link "${ZOOCODE_MODEL_CLOUD:-}" "ZooCode"
link "${KILOCODE_MODEL:-}" "KiloCode"
link "${KILOCODE_MODEL_CLOUD:-}" "KiloCode"
link "${AIDER_MODEL:-}" "Aider"
link "${AIDER_WEAK_MODEL:-}" "Aider"
link "${AIDER_EDITOR_MODEL:-}" "Aider"
link "${ZED_MODEL:-}" "Zed"
link "${CURSOR_MODEL:-}" "Cursor"
link "${CURSOR_MODEL_CLOUD:-}" "Cursor"

if declare -p OPENCODE_AGENTS &>/dev/null 2>&1; then
    for role in "${!OPENCODE_AGENTS[@]}"; do
        link "${OPENCODE_AGENTS[$role]}" "OpenCode"
    done
fi
if declare -p CONTINUE_ROLES &>/dev/null 2>&1; then
    for role in "${!CONTINUE_ROLES[@]}"; do
        link "${CONTINUE_ROLES[$role]}" "Continue"
    done
fi
if declare -p CLAUDE_CODE &>/dev/null 2>&1; then
    for role in "${!CLAUDE_CODE[@]}"; do
        link "${CLAUDE_CODE[$role]}" "ClaudeCode"
    done
fi

# Collect and sort model names
ALL_MODELS=()
for m in "${!TOOLS_BY_MODEL[@]}"; do ALL_MODELS+=("$m"); done
IFS=$'\n' ALL_MODELS=($(sort -f <<<"${ALL_MODELS[*]}")); IFS=$' \t\n'

# Cloud model refs
CLOUD_REFS=()
if declare -p OPENROUTER_MODELS &>/dev/null 2>&1; then
    CLOUD_REFS=("${OPENROUTER_MODELS[@]}")
fi

TOOLS_LIST=(Cline ZooCode KiloCode Aider Zed Cursor OpenCode Continue ClaudeCode)

sanitize() { echo "${1//[^a-zA-Z0-9]/_}"; }

# Generate markdown
OUTPUT="$PROFILES_DIR/$PROFILE/model-map.md"
{
    echo "# Model Map — $PROFILE"
    echo ""
    echo '```mermaid'
    echo "graph TB"
    echo ""

    # Local model nodes
    for m in "${ALL_MODELS[@]}"; do
        mid=$(sanitize "$m")
        local_label=$(echo "$m" | sed 's/:/\\:/g')
        echo "    ${mid}(\"${local_label}\")"
    done

    echo ""
    echo "    %% Tool nodes → config destinations"
    echo "    Cline[\"Cline → VS Code settings.json\"]"
    echo "    ZooCode[\"ZooCode → VS Code settings.json\"]"
    echo "    KiloCode[\"KiloCode → ~/.kilo/kilo.jsonc\"]"
    echo "    Aider[\"Aider → ~/.aider.conf.yml\"]"
    echo "    Zed[\"Zed → ~/.config/zed/settings.json\"]"
    echo "    Cursor[\"Cursor → Cursor settings.json\"]"
    echo "    OpenCode[\"OpenCode → ~/.config/opencode/opencode.jsonc\"]"
    echo "    Continue[\"Continue → ~/.continue/config.yaml\"]"
    echo "    ClaudeCode[\"ClaudeCode → ~/.claude/settings.json\"]"

    echo ""
    echo "    %% Edges: model → tool"
    for m in "${ALL_MODELS[@]}"; do
        mid=$(sanitize "$m")
        tools="${TOOLS_BY_MODEL[$m]}"
        IFS=',' read -ra tlist <<< "$tools"
        for t in "${tlist[@]}"; do
            tid=$(sanitize "$t")
            echo "    ${mid} --> ${tid}"
        done
    done

    echo ""
    echo "    %% Styles"
    echo "    classDef local fill:#1a1a2e,stroke:#e94560,color:#fff"
    echo "    classDef tool fill:#1a3a5c,stroke:#00d2ff,color:#fff"
    echo "    classDef cloud fill:#2d1b2e,stroke:#9b59b6,color:#ddd"
    for m in "${ALL_MODELS[@]}"; do
        mid=$(sanitize "$m")
        if [[ "$m" == *":cloud"* || "$m" == *"kimi"* || "$m" == *"k2.6"* ]]; then
            echo "    class ${mid} cloud"
        else
            echo "    class ${mid} local"
        fi
    done
    for t in "${TOOLS_LIST[@]}"; do
        tid=$(sanitize "$t")
        echo "    class ${tid} tool"
    done

    echo ""
    if [[ ${#CLOUD_REFS[@]} -gt 0 ]]; then
        echo "    %% OpenRouter reference models"
        echo "    subgraph OpenRouterAvailable [\"OpenRouter (available)\"]"
        for cm in "${CLOUD_REFS[@]}"; do
            cid="or_$(sanitize "$cm")"
            echo "    ${cid}(\"${cm}\")"
        done
        echo "    end"
    fi

    echo '```'
    echo ""
    echo "Generated by \`generate-model-map.sh\` for profile \`$PROFILE\`."
    echo "Edit \`models.sh\` and re-run to regenerate."
} > "$OUTPUT"

echo "✅ Wrote $OUTPUT"
