#!/bin/bash
# Oh My Zsh Standardization Script
# Deploys identical Oh My Zsh setup across all machines: dx1, ds9, enterprise, discovery
#
# Usage: bash install-ohmyzsh-standard.sh
# Run on EACH machine to ensure identical configuration

set -e

echo "=== Oh My Zsh Standardization ==="
echo "Machine: $(hostname)"
echo ""

# Check if running as correct user
if [ "$(whoami)" != "isaac" ]; then
    echo "ERROR: Must run as user 'isaac'"
    exit 1
fi

# Install Oh My Zsh if not present
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "Installing Oh My Zsh..."
    RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
    echo "✓ Oh My Zsh already installed"
fi

# Install powerlevel10k theme
P10K_DIR="$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
if [ ! -d "$P10K_DIR" ]; then
    echo "Installing powerlevel10k theme..."
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$P10K_DIR"
else
    echo "✓ powerlevel10k already installed"
fi

# Install zsh-autosuggestions plugin
ZSH_AUTOSUGGEST_DIR="$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
if [ ! -d "$ZSH_AUTOSUGGEST_DIR" ]; then
    echo "Installing zsh-autosuggestions..."
    git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_AUTOSUGGEST_DIR"
else
    echo "✓ zsh-autosuggestions already installed"
fi

# Install zsh-syntax-highlighting plugin
ZSH_SYNTAX_DIR="$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
if [ ! -d "$ZSH_SYNTAX_DIR" ]; then
    echo "Installing zsh-syntax-highlighting..."
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_SYNTAX_DIR"
else
    echo "✓ zsh-syntax-highlighting already installed"
fi

# Create zshrc.d directory if not exists
mkdir -p "$HOME/.zshrc.d"
mkdir -p "$HOME/.profile.d"

# Deploy Oh My Zsh configuration
echo "Deploying Oh My Zsh configuration..."
cat > "$HOME/.zshrc.d/_omz" << 'OMZ_CONFIG'
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
[ -f "$ZSH/oh-my-zsh.sh" ] || return 0

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
    git
    bundler
    macos
    rake
    ruby
    aws
    zsh-autosuggestions
    zsh-syntax-highlighting
)

# Source Oh My Zsh
source $ZSH/oh-my-zsh.sh
OMZ_CONFIG

# Deploy powerlevel10k configuration
echo "Deploying powerlevel10k configuration..."
cat > "$HOME/.p10k.zsh" << 'P10K_CONFIG'
# Generated by Powerlevel10k configuration wizard on 2026-04-15 at 13:53 EDT.
# Based on romkatv/powerlevel10k/config/p10k-lean.zsh, checksum 2674.
# Wizard options: powerline, ascii, lean, 24h time, 2 lines, solid, light-ornaments,
# sparse, fluent, transient_prompt, instant_prompt=verbose.
# Type `p10k configure` to generate another config.

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  (( ! $+functions[p10k] )) || p10k reload
}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
P10K_CONFIG

# Ensure .zshrc sources p10k config
if ! grep -q "p10k.zsh" "$HOME/.zshrc"; then
    echo "Adding p10k config to .zshrc..."
    cat >> "$HOME/.zshrc" << 'ZSHRC_APPEND'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
ZSHRC_APPEND
fi

# Set locale
echo "Setting locale..."
cat >> "$HOME/.zshrc" << 'LOCALE_CONFIG'

# Locale settings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
LOCALE_CONFIG

echo ""
echo "=== Installation Complete ==="
echo ""
echo "Next steps:"
echo "1. Open a new terminal or run: exec zsh"
echo "2. If powerlevel10k wizard doesn't run automatically, run: p10k configure"
echo "3. Verify with: echo \$ZSH_THEME"
echo ""
echo "Configuration deployed:"
echo "  - Oh My Zsh: $HOME/.oh-my-zsh"
echo "  - Theme: powerlevel10k/powerlevel10k"
echo "  - Plugins: git, bundler, macos, rake, ruby, aws, zsh-autosuggestions, zsh-syntax-highlighting"
echo "  - Config: $HOME/.zshrc.d/_omz"
echo "  - p10k: $HOME/.p10k.zsh"
echo ""
